adds .webloc support
gingerbeardman/stapler pull request #14
Opened 2024-08-15 10:00 UTC by kristofer

Adds .webloc support for dropping a web url from browser into a .stapled file. Launching works as well without mods.

It allows a user to include web bookmarks into Stapler files, along with the local files.

2024-08-15 15:20 UTC, kristofer commented
I guess I should add, I was unable to get the weblog stuff to work on 13.6 Ventura. But I see your example in the readme has a weblog item in it.

2024-08-19 22:15 UTC, gingerbeardman commented
Also, sorry this will need to be rebased as I've just implemented some changes to how things are added and launched—sorry!

2024-08-20 21:35 UTC, gingerbeardman requested changes
Please make changes to StaplerApp.swift based on the current source.

And please remove all other files that are unrelated to the .webloc change — thanks!

2024-08-20 21:35 UTC, gingerbeardman commented on Stapler.xcodeproj/project.pbxproj
Please remove this file from the PR

2024-08-20 21:35 UTC, gingerbeardman commented on Stapler.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
Please remove this file from the PR

2024-08-20 21:35 UTC, gingerbeardman commented on Stapler.xcodeproj/project.xcworkspace/xcuserdata/kristofer.xcuserdatad/UserInterfaceState.xcuserstate
Please remove this file from the PR

2024-08-20 21:35 UTC, gingerbeardman commented on Stapler.xcodeproj/xcuserdata/kristofer.xcuserdatad/xcdebugger/Breakpoints_v2.xcbkptlist
Please remove this file from the PR

2024-08-20 21:35 UTC, gingerbeardman commented on Stapler.xcodeproj/xcuserdata/kristofer.xcuserdatad/xcschemes/xcschememanagement.plist
Please remove this file from the PR

2024-08-20 21:35 UTC, gingerbeardman commented on .DS_Store
Please remove this file from the PR

2024-08-20 21:36 UTC, gingerbeardman commented on Stapler/StaplerApp.swift
Please rebase this against current source. Thanks!

2024-08-20 21:37 UTC, gingerbeardman commented
> I guess I should add, I was unable to get the weblog stuff to work on 13.6 Ventura. But I see your example in the readme has a weblog item in it.

My webloc item was dragged from Safari > Finder > Stapler

2024-08-23 18:43 UTC, kristofer commented
- finally seeing this, will do. just give me a day or few. thanks! (ps and sorry, i thought i had reduced it to just the one file)

2024-08-26 12:41 UTC, gingerbeardman commented
No rush at all! I think this change will also get us the ability to drag and drop email addresses in the same way #36

2024-08-27 13:10 UTC, kristofer commented
Glad you asked me to clean this up.

So the .webloc I'm saving in the StaplerDoc is merely a file (containing the actual target URL) in the *temporary directory* of the app. SO, when that gets deleted, the weblog file is gone. Bad.

I think there are two options. 

- make AliasItem handle other things than just file-urls - like web urls and email addresses and what-not. the alias would have a content-type field, for each species (MIME types?) 
- make a place where .webloc (and other non-file-urls) get copied when created so they aren't lost when the TMP dir changes. (yuck!) 

hmm.

2024-08-27 13:14 UTC, kristofer commented
Since the alias just gets JSON'd when saved, seems like adding typing to them makes the most send.

2024-08-27 16:31 UTC, gingerbeardman commented
See https://github.com/gingerbeardman/stapler/issues/18 for an explanation of filesystem bookmarks.

I wonder if we can use file:// and mailto:// URLs?

I'll give it some thought.

2024-08-27 19:06 UTC, kristofer commented
lemme untangle this mess

2024-08-27 19:43 UTC, kristofer commented
okay, I think I've cleaned it all up, along with pulling in all your latest commits.

2026-06-19 07:50 UTC, gingerbeardman commented
A bit late on this one, but I reimplemented this in the latest code. But thanks so much!

2026-06-19 07:50 UTC, closed without merging